# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dive < Formula
  desc "A tool for exploring layers in a docker image"
  homepage "https://github.com/pRizz/dive/"
  version "14.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pRizz/dive/releases/download/v14.8/dive_14.8_darwin_amd64.tar.gz"
      sha256 "4544d5b0d7bd39acc7dbecfd5840f648330b666acd712130b29ac1eb65995810"

      def install
        bin.install "dive"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pRizz/dive/releases/download/v14.8/dive_14.8_darwin_arm64.tar.gz"
      sha256 "004a96ca299d2671444f9603a40c897f1311b9b59f8d0e398044427463de9534"

      def install
        bin.install "dive"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pRizz/dive/releases/download/v14.8/dive_14.8_linux_amd64.tar.gz"
        sha256 "09f1dc00556857cb6314cfe1c080fcdccb122a8be6f16d418fd8626c9ecef4f6"

        def install
          bin.install "dive"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pRizz/dive/releases/download/v14.8/dive_14.8_linux_arm64.tar.gz"
        sha256 "8e700f386e2770eea47636ac7775b4bc565e2b0862cbcbb1c437e0b9d6d4e131"

        def install
          bin.install "dive"
        end
      end
    end
  end
end
