# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dive < Formula
  desc "A tool for exploring layers in a docker image"
  homepage "https://github.com/pRizz/dive/"
  version "0.14.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pRizz/dive/releases/download/v0.14.7/dive_0.14.7_darwin_amd64.tar.gz"
      sha256 "1c1675a6cb7f4fb095350558511c61877c459845c6c89edebd14874250d5c63d"

      def install
        bin.install "dive"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pRizz/dive/releases/download/v0.14.7/dive_0.14.7_darwin_arm64.tar.gz"
      sha256 "6c0081530b0c23652d46cc1bf587d8caa6485ca07f3731dbd6c452ca7018fca4"

      def install
        bin.install "dive"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pRizz/dive/releases/download/v0.14.7/dive_0.14.7_linux_amd64.tar.gz"
        sha256 "aa6b539a2cde76d67d849c5e92b4ef9b08ee784e53c6ed26d05c515f441b615e"

        def install
          bin.install "dive"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pRizz/dive/releases/download/v0.14.7/dive_0.14.7_linux_arm64.tar.gz"
        sha256 "95377c0439ce86c7a7b55c6d8c26b32d0f6c37b14b42414195b30f74a7b8b12d"

        def install
          bin.install "dive"
        end
      end
    end
  end
end
